import Navbar from '@/components/Navbar';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body 
        className={`${inter.className}`}
      >
        <Navbar />
        <main className='container mx-auto h-[calc(100vh -7rem)] flex justify-center items-center'>
          {children}
        </main>
      </body>
    </html>
  )
}
